// autogenerated from SchemaBinder

package org.jbrain.tcpser4j.binding;

/**
 * Title: ActionList
 * Description: Description of the class
 * @author SchemaBinder
 * @version 1.0
 * 
 */

public class ActionList implements java.io.Serializable {
    private static final String sObjName="ActionList";
    public static final ActionList VALUE_answer = new ActionList("answer");
    public static final ActionList VALUE_connect = new ActionList("connect");
    public static final ActionList VALUE_busy = new ActionList("busy");
    public static final ActionList VALUE_inactivity = new ActionList("inactivity");
    public static final ActionList VALUE_no_answer = new ActionList("no_answer");


    private static java.util.HashMap _memberTable = init();

    private String _sValue = null;

    private ActionList(String val) {
        _sValue=val;
    }

    private static java.util.HashMap init() {
        java.util.HashMap members=new java.util.HashMap();
        members.put("answer", VALUE_answer);
        members.put("connect", VALUE_connect);
        members.put("busy", VALUE_busy);
        members.put("inactivity", VALUE_inactivity);
        members.put("no_answer", VALUE_no_answer);
        return members;
    }

    public String toString() {
        return _sValue;
    }

    public static ActionList valueOf(String type) {
        try {
            // quick fix for leading zero supression.  Fix later jlb
            type=String.valueOf(Integer.parseInt(type));
        } catch (Exception e) {;}
        return (ActionList)_memberTable.get(type);
    }

    public java.util.Iterator iterator() {
        return _memberTable.values().iterator();
    }

}
