// autogenerated from SchemaBinder

package org.jbrain.tcpser4j.binding;

/**
 * Title: Line
 * Description: Description of the class
 * @author SchemaBinder
 * @version 1.0
 * 
 */

public class Line implements java.io.Serializable {
    private static final String sObjName="Line";
    private Integer _oPort=null;


    public Line() {
    }

     /**
      * Title: Line
      * Description: Description of the constructor
      * 
      */

    public Line(org.dom4j.Element el) throws Exception {
        this();
        readXML(el);
    }

    public Integer getPort() {
        return _oPort;
    }

    public void setPort(Integer o) {
        _oPort = o;
    }


     /**
      * Title: validate
      * Description: Description of the method
      * 
      */

    public boolean validate() throws Exception {
        return true;
    }

     /**
      * Title: readXML
      * Description: Parses XML into Object instance
      * 
      */

    public void readXML(org.dom4j.Element el) throws Exception {
        String name,value;
        org.dom4j.Element node=el;

        if (el.attribute("port") != null)
                setPort(org.jbrain.xml.binding._TypeConverter.parseInteger(el.attribute("port").getText(), sObjName, "Port"));
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML() throws Exception {
        return writeXML(sObjName);
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML(String name) throws Exception {
        org.dom4j.Element el = org.dom4j.DocumentHelper.createElement(name);

        if(getPort() != null)
            el.addAttribute("port", org.jbrain.xml.binding._TypeConverter.buildInteger(getPort()));
        return el;
    }

}
