// autogenerated from SchemaBinder

package org.jbrain.tcpser4j.binding;

/**
 * Title: MessageInfo
 * Description: Description of the class
 * @author SchemaBinder
 * @version 1.0
 * 
 */

public class MessageInfo implements java.io.Serializable {
    private static final String sObjName="MessageInfo";
    private ActionList _oAction=null;
    private DirectionList _oDirection=null;
    private String _oLocation=null;


    public MessageInfo() {
    }

     /**
      * Title: MessageInfo
      * Description: Description of the constructor
      * 
      */

    public MessageInfo(org.dom4j.Element el) throws Exception {
        this();
        readXML(el);
    }

    public ActionList getAction() {
        return _oAction;
    }

    public void setAction(ActionList o) {
        _oAction = o;
    }

    public DirectionList getDirection() {
        return _oDirection;
    }

    public void setDirection(DirectionList o) {
        _oDirection = o;
    }

    public String getLocation() {
        return _oLocation;
    }

    public void setLocation(String o) {
        _oLocation = o;
    }


     /**
      * Title: validate
      * Description: Description of the method
      * 
      */

    public boolean validate() throws Exception {
        return true;
    }

     /**
      * Title: readXML
      * Description: Parses XML into Object instance
      * 
      */

    public void readXML(org.dom4j.Element el) throws Exception {
        String name,value;
        org.dom4j.Element node=el;

        if (el.attribute("action") != null)
                setAction(ActionList.valueOf(el.attribute("action").getText()));
        if (el.attribute("direction") != null)
                setDirection(DirectionList.valueOf(el.attribute("direction").getText()));
        if (el.attribute("location") != null)
                setLocation(el.attribute("location").getText());
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML() throws Exception {
        return writeXML(sObjName);
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML(String name) throws Exception {
        org.dom4j.Element el = org.dom4j.DocumentHelper.createElement(name);

        if(getAction() != null)
            el.addAttribute("action", getAction().toString());
        if(getDirection() != null)
            el.addAttribute("direction", getDirection().toString());
        if(getLocation() != null)
            el.addAttribute("location", getLocation());
        return el;
    }

}
