// autogenerated from SchemaBinder

package org.jbrain.tcpser4j.binding;

/**
 * Title: Entry
 * Description: Description of the class
 * @author SchemaBinder
 * @version 1.0
 * 
 */

public class Entry implements java.io.Serializable {
    private static final String sObjName="Entry";
    private String _oNumber=null;
    private String _oValue=null;


    public Entry() {
    }

     /**
      * Title: Entry
      * Description: Description of the constructor
      * 
      */

    public Entry(org.dom4j.Element el) throws Exception {
        this();
        readXML(el);
    }

    public String getNumber() {
        return _oNumber;
    }

    public void setNumber(String o) {
        _oNumber = o;
    }

    public String getValue() {
        return _oValue;
    }

    public void setValue(String o) {
        _oValue = o;
    }


     /**
      * Title: validate
      * Description: Description of the method
      * 
      */

    public boolean validate() throws Exception {
        return true;
    }

     /**
      * Title: readXML
      * Description: Parses XML into Object instance
      * 
      */

    public void readXML(org.dom4j.Element el) throws Exception {
        String name,value;
        org.dom4j.Element node=el;

        if (el.attribute("number") != null)
                setNumber(el.attribute("number").getText());
        if (el.attribute("value") != null)
                setValue(el.attribute("value").getText());
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML() throws Exception {
        return writeXML(sObjName);
    }

     /**
      * Title: writeXML
      * Description: Creates XML from Object instance
      * 
      */

    public org.dom4j.Element writeXML(String name) throws Exception {
        org.dom4j.Element el = org.dom4j.DocumentHelper.createElement(name);

        if(getNumber() != null)
            el.addAttribute("number", getNumber());
        if(getValue() != null)
            el.addAttribute("value", getValue());
        return el;
    }

}
